import json
import os
import re
import sys
from datetime import datetime
from pathlib import Path

from PySide6.QtCore import Qt, QProcess, QTimer
from PySide6.QtGui import QAction, QColor, QPalette
from PySide6.QtWidgets import (
    QApplication,
    QButtonGroup,
    QCheckBox,
    QFileDialog,
    QFrame,
    QGridLayout,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QMainWindow,
    QMessageBox,
    QPushButton,
    QProgressBar,
    QRadioButton,
    QScrollArea,
    QSizePolicy,
    QStackedWidget,
    QSystemTrayIcon,
    QVBoxLayout,
    QWidget,
    QMenu,
)


APP_NAME = "YouWizard"


def root_dir() -> Path:
    return Path(__file__).resolve().parent.parent


ROOT = root_dir()
BIN = ROOT / "bin"
SETTINGS_DIR = ROOT / "settings"
SETTINGS_FILE = SETTINGS_DIR / "settings.json"

YTDLP = BIN / "yt-dlp.exe"
FFMPEG = BIN / "ffmpeg.exe"
FFPROBE = BIN / "ffprobe.exe"


DEFAULT_SETTINGS = {
    "_warning_ru": "ВНИМАНИЕ: если вы не знаете, за что отвечает параметр, не изменяйте этот файл вручную.",
    "_warning_en": "WARNING: if you do not know what a setting does, do not edit this file manually.",
    "app": {
        "close_to_tray": True
    },
    "downloads": {
        "download_folder": "downloads",
        "default_mode": "video",
        "show_high_res_options": False,
        "recent_downloads": []
    },
    "audio": {
        "format": "mp3",
        "quality": "192K"
    },
    "logs": {
        "enabled": True,
        "folder": "settings/logs",
        "cleanup_interval_minutes": 60,
        "keep_last_logs": 20
    }
}


def deep_update(base: dict, patch: dict) -> None:
    for key, value in patch.items():
        if isinstance(value, dict) and isinstance(base.get(key), dict):
            deep_update(base[key], value)
        else:
            base[key] = value


def save_settings(settings: dict) -> None:
    SETTINGS_DIR.mkdir(parents=True, exist_ok=True)
    SETTINGS_FILE.write_text(
        json.dumps(settings, ensure_ascii=False, indent=4),
        encoding="utf-8"
    )


def load_settings() -> dict:
    SETTINGS_DIR.mkdir(parents=True, exist_ok=True)

    if not SETTINGS_FILE.exists():
        save_settings(DEFAULT_SETTINGS)
        return json.loads(json.dumps(DEFAULT_SETTINGS))

    try:
        data = json.loads(SETTINGS_FILE.read_text(encoding="utf-8"))

        if not isinstance(data, dict):
            raise ValueError("settings.json is not object")

        result = json.loads(json.dumps(DEFAULT_SETTINGS))
        deep_update(result, data)
        return result

    except Exception:
        broken = SETTINGS_DIR / "settings.broken.json"

        try:
            SETTINGS_FILE.replace(broken)
        except Exception:
            pass

        save_settings(DEFAULT_SETTINGS)
        return json.loads(json.dumps(DEFAULT_SETTINGS))


def app_path(text: str) -> Path:
    text = text.strip()

    if not text:
        return ROOT / "downloads"

    path = Path(text)

    if path.is_absolute():
        return path

    return ROOT / path


def logs_dir(settings: dict) -> Path:
    folder = settings.get("logs", {}).get("folder", "settings/logs")
    path = app_path(folder)
    path.mkdir(parents=True, exist_ok=True)
    return path


def cleanup_logs(settings: dict) -> None:
    folder = logs_dir(settings)

    try:
        keep = int(settings.get("logs", {}).get("keep_last_logs", 20))
    except Exception:
        keep = 20

    keep = max(1, keep)

    files = sorted(
        folder.glob("*.txt"),
        key=lambda p: p.stat().st_mtime,
        reverse=True
    )

    for file in files[keep:]:
        try:
            file.unlink()
        except Exception:
            pass


def newest_file(folder: Path) -> Path | None:
    if not folder.exists():
        return None

    exts = {".mp4", ".mp3", ".m4a", ".webm", ".mkv"}
    files = [p for p in folder.iterdir() if p.is_file() and p.suffix.lower() in exts]

    if not files:
        return None

    return max(files, key=lambda p: p.stat().st_mtime)


def add_recent(settings: dict, file: Path) -> None:
    recent = settings.setdefault("downloads", {}).setdefault("recent_downloads", [])

    recent.insert(0, {
        "name": file.name,
        "path": str(file),
        "date": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    })

    clean = []
    used = set()

    for item in recent:
        path = item.get("path", "")

        if not path or path in used:
            continue

        used.add(path)
        clean.append(item)

    settings["downloads"]["recent_downloads"] = clean[:5]
    save_settings(settings)


def open_path(path: Path) -> None:
    try:
        os.startfile(path)
    except Exception:
        QMessageBox.warning(None, "Ошибка", f"Не удалось открыть:\n{path}")


def apply_dark_palette(app: QApplication) -> None:
    palette = QPalette()

    palette.setColor(QPalette.Window, QColor("#1E1E1E"))
    palette.setColor(QPalette.WindowText, QColor("#F5F5F7"))
    palette.setColor(QPalette.Base, QColor("#151515"))
    palette.setColor(QPalette.AlternateBase, QColor("#242426"))
    palette.setColor(QPalette.ToolTipBase, QColor("#2A2A2D"))
    palette.setColor(QPalette.ToolTipText, QColor("#FFFFFF"))
    palette.setColor(QPalette.Text, QColor("#F5F5F7"))
    palette.setColor(QPalette.Button, QColor("#303034"))
    palette.setColor(QPalette.ButtonText, QColor("#FFFFFF"))
    palette.setColor(QPalette.BrightText, QColor("#FFFFFF"))
    palette.setColor(QPalette.Link, QColor("#0A84FF"))
    palette.setColor(QPalette.Highlight, QColor("#0A84FF"))
    palette.setColor(QPalette.HighlightedText, QColor("#FFFFFF"))

    app.setPalette(palette)


def make_scroll_page(page: QWidget) -> QScrollArea:
    scroll = QScrollArea()
    scroll.setObjectName("PageScroll")
    scroll.setWidgetResizable(True)
    scroll.setFrameShape(QFrame.NoFrame)
    scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
    scroll.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
    scroll.setWidget(page)
    return scroll


class Logger:
    def __init__(self, settings: dict):
        self.enabled = bool(settings.get("logs", {}).get("enabled", True))
        self.file = logs_dir(settings) / f"youwizard_{datetime.now().strftime('%Y-%m-%d_%H-%M-%S')}.txt"

        self.write("=== YouWizard started ===")
        self.write(f"Root: {ROOT}")
        self.write(f"Time: {datetime.now().isoformat(timespec='seconds')}")
        self.write("")

    def write(self, text: str) -> None:
        if not self.enabled:
            return

        try:
            with self.file.open("a", encoding="utf-8") as f:
                f.write(text.rstrip() + "\n")
        except Exception:
            pass

    def block(self, text: str) -> None:
        for line in text.splitlines():
            self.write(line)


class Card(QFrame):
    def __init__(self):
        super().__init__()
        self.setObjectName("Card")
        self.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Maximum)


class NavButton(QPushButton):
    def __init__(self, text: str):
        super().__init__(text)
        self.setCheckable(True)
        self.setMinimumHeight(44)
        self.setCursor(Qt.PointingHandCursor)


class QualityButton(QRadioButton):
    def __init__(self, text: str, height_value: int | None):
        super().__init__(text)
        self.height_value = height_value
        self.setObjectName("QualityButton")
        self.setMinimumHeight(42)
        self.setCursor(Qt.PointingHandCursor)
        self.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)


class RecentList(Card):
    def __init__(self, window: "MainWindow", title: str):
        super().__init__()
        self.window = window

        self.layout = QVBoxLayout(self)
        self.layout.setContentsMargins(16, 16, 16, 16)
        self.layout.setSpacing(10)

        label = QLabel(title)
        label.setObjectName("SectionTitle")
        self.layout.addWidget(label)

        self.items = QVBoxLayout()
        self.items.setSpacing(8)
        self.layout.addLayout(self.items)

        self.refresh()

    def clear_items(self) -> None:
        while self.items.count():
            item = self.items.takeAt(0)
            widget = item.widget()

            if widget:
                widget.deleteLater()

    def refresh(self) -> None:
        self.clear_items()

        recent = self.window.settings.get("downloads", {}).get("recent_downloads", [])[:5]

        if not recent:
            empty = QLabel("Пока ничего не скачано.")
            empty.setObjectName("Muted")
            empty.setWordWrap(True)
            self.items.addWidget(empty)
            return

        for item in recent:
            row = QFrame()
            row.setObjectName("RecentRow")

            row_layout = QHBoxLayout(row)
            row_layout.setContentsMargins(12, 8, 12, 8)
            row_layout.setSpacing(10)

            name = item.get("name", "Файл")
            date = item.get("date", "")
            path = item.get("path", "")

            text = QLabel(f"{name}\n{date}")
            text.setObjectName("RecentText")
            text.setWordWrap(True)

            open_btn = QPushButton("Открыть")
            open_btn.setFixedWidth(105)
            open_btn.clicked.connect(lambda checked=False, p=path: self.open_file(p))

            row_layout.addWidget(text, 1)
            row_layout.addWidget(open_btn)

            self.items.addWidget(row)

    def open_file(self, path: str) -> None:
        p = Path(path)

        if p.exists():
            open_path(p)
        else:
            QMessageBox.warning(self, "Файл не найден", "Файл удалён или перемещён.")


class DownloadPage(QWidget):
    def __init__(self, window: "MainWindow"):
        super().__init__()
        self.window = window
        self.process: QProcess | None = None
        self.current_folder: Path | None = None
        self.selected_quality: int | None = None

        layout = QVBoxLayout(self)
        layout.setContentsMargins(24, 22, 24, 22)
        layout.setSpacing(12)

        title = QLabel("Скачать")
        title.setObjectName("PageTitle")

        subtitle = QLabel("Видео скачивается через yt-dlp. MP4 собирается через ffmpeg без лишнего перекодирования.")
        subtitle.setObjectName("Muted")
        subtitle.setWordWrap(True)

        self.url = QLineEdit()
        self.url.setPlaceholderText("Вставь ссылку на видео")
        self.url.setMinimumHeight(46)

        self.mode_card = Card()
        mode_layout = QVBoxLayout(self.mode_card)
        mode_layout.setContentsMargins(16, 16, 16, 16)
        mode_layout.setSpacing(8)

        mode_title = QLabel("Что скачать")
        mode_title.setObjectName("SectionTitle")

        self.video_radio = QRadioButton("Видео")
        self.audio_radio = QRadioButton("Только аудио")

        self.mode_group = QButtonGroup(self)
        self.mode_group.addButton(self.video_radio)
        self.mode_group.addButton(self.audio_radio)

        if self.window.settings["downloads"].get("default_mode") == "audio":
            self.audio_radio.setChecked(True)
        else:
            self.video_radio.setChecked(True)

        self.video_radio.toggled.connect(self.update_mode)

        mode_layout.addWidget(mode_title)
        mode_layout.addWidget(self.video_radio)
        mode_layout.addWidget(self.audio_radio)

        self.quality_card = Card()
        quality_layout = QVBoxLayout(self.quality_card)
        quality_layout.setContentsMargins(16, 16, 16, 16)
        quality_layout.setSpacing(10)

        quality_title = QLabel("Качество")
        quality_title.setObjectName("SectionTitle")

        self.quality_group = QButtonGroup(self)
        self.quality_group.setExclusive(True)

        self.quality_grid = QGridLayout()
        self.quality_grid.setHorizontalSpacing(8)
        self.quality_grid.setVerticalSpacing(8)

        quality_hint = QLabel("2K / 4K / 8K скрыты по умолчанию. Включаются в настройках.")
        quality_hint.setObjectName("Muted")
        quality_hint.setWordWrap(True)

        quality_layout.addWidget(quality_title)
        quality_layout.addLayout(self.quality_grid)
        quality_layout.addWidget(quality_hint)

        self.rebuild_quality_buttons()

        self.audio_card = Card()
        audio_layout = QVBoxLayout(self.audio_card)
        audio_layout.setContentsMargins(16, 16, 16, 16)
        audio_layout.setSpacing(8)

        audio_title = QLabel("Формат аудио")
        audio_title.setObjectName("SectionTitle")

        self.mp3_radio = QRadioButton("MP3")
        self.m4a_radio = QRadioButton("M4A")

        self.audio_group = QButtonGroup(self)
        self.audio_group.addButton(self.mp3_radio)
        self.audio_group.addButton(self.m4a_radio)

        if self.window.settings["audio"].get("format") == "m4a":
            self.m4a_radio.setChecked(True)
        else:
            self.mp3_radio.setChecked(True)

        audio_layout.addWidget(audio_title)
        audio_layout.addWidget(self.mp3_radio)
        audio_layout.addWidget(self.m4a_radio)

        folder_card = Card()
        folder_layout = QVBoxLayout(folder_card)
        folder_layout.setContentsMargins(16, 16, 16, 16)
        folder_layout.setSpacing(10)

        folder_title = QLabel("Папка загрузок")
        folder_title.setObjectName("SectionTitle")

        folder_row = QHBoxLayout()
        folder_row.setSpacing(10)

        self.folder = QLineEdit()
        self.folder.setMinimumHeight(46)
        self.folder.setText(self.window.download_folder())

        choose = QPushButton("Выбрать")
        choose.setMinimumHeight(46)
        choose.clicked.connect(self.choose_folder)

        folder_row.addWidget(self.folder, 1)
        folder_row.addWidget(choose)

        folder_layout.addWidget(folder_title)
        folder_layout.addLayout(folder_row)

        buttons = QHBoxLayout()
        buttons.setSpacing(10)

        self.download_btn = QPushButton("Скачать")
        self.download_btn.setObjectName("Primary")
        self.download_btn.setMinimumHeight(48)
        self.download_btn.clicked.connect(self.start_download)

        self.stop_btn = QPushButton("Остановить")
        self.stop_btn.setMinimumHeight(48)
        self.stop_btn.setEnabled(False)
        self.stop_btn.clicked.connect(self.stop_download)

        buttons.addWidget(self.download_btn)
        buttons.addWidget(self.stop_btn)

        self.progress = QProgressBar()
        self.progress.setMinimumHeight(26)
        self.progress.setValue(0)
        self.progress.setTextVisible(True)

        self.status = QLabel("Готов к работе.")
        self.status.setObjectName("Muted")
        self.status.setWordWrap(True)

        self.recent = RecentList(self.window, "Последние 5 загруженных файлов")

        layout.addWidget(title)
        layout.addWidget(subtitle)
        layout.addWidget(self.url)
        layout.addWidget(self.mode_card)
        layout.addWidget(self.quality_card)
        layout.addWidget(self.audio_card)
        layout.addWidget(folder_card)
        layout.addLayout(buttons)
        layout.addWidget(self.progress)
        layout.addWidget(self.status)
        layout.addWidget(self.recent)
        layout.addStretch()

        self.update_mode()

    def clear_quality_grid(self) -> None:
        while self.quality_grid.count():
            item = self.quality_grid.takeAt(0)
            widget = item.widget()

            if widget:
                self.quality_group.removeButton(widget)
                widget.deleteLater()

    def rebuild_quality_buttons(self) -> None:
        self.clear_quality_grid()

        if self.window.settings["downloads"].get("show_high_res_options", False):
            qualities = [
                ("Лучшее", None),
                ("8K", 4320),
                ("4K", 2160),
                ("2K", 1440),
                ("1080p", 1080),
                ("720p", 720),
                ("480p", 480),
                ("360p", 360),
            ]
        else:
            qualities = [
                ("Лучшее", None),
                ("1080p", 1080),
                ("720p", 720),
                ("480p", 480),
                ("360p", 360),
            ]

        columns = 4

        for i, (name, height) in enumerate(qualities):
            btn = QualityButton(name, height)
            btn.toggled.connect(lambda checked, b=btn: self.set_quality(b, checked))

            self.quality_group.addButton(btn)
            self.quality_grid.addWidget(btn, i // columns, i % columns)

            if i == 0:
                btn.setChecked(True)

        for col in range(columns):
            self.quality_grid.setColumnStretch(col, 1)

    def set_quality(self, button: QualityButton, checked: bool) -> None:
        if checked:
            self.selected_quality = button.height_value

    def refresh_recent(self) -> None:
        self.recent.refresh()

    def update_mode(self) -> None:
        is_video = self.video_radio.isChecked()
        self.quality_card.setVisible(is_video)
        self.audio_card.setVisible(not is_video)

    def choose_folder(self) -> None:
        folder = QFileDialog.getExistingDirectory(
            self,
            "Выбрать папку загрузок",
            str(app_path(self.folder.text())),
            QFileDialog.Option.DontUseNativeDialog
        )

        if folder:
            self.folder.setText(folder)

    def check_tools(self) -> bool:
        missing = []

        if not YTDLP.exists():
            missing.append(str(YTDLP))

        if not FFMPEG.exists():
            missing.append(str(FFMPEG))

        if missing:
            QMessageBox.critical(
                self,
                "Не найдены инструменты",
                "Не найдены файлы:\n\n" + "\n".join(missing) + "\n\nПоложи их в папку bin."
            )
            return False

        return True

    def video_command(self, url: str, folder: Path) -> list[str]:
        if self.selected_quality is None:
            fmt = (
                "bv*[vcodec^=avc1][ext=mp4][height>=360]+ba[ext=m4a]/"
                "bv*[ext=mp4][height>=360]+ba[ext=m4a]/"
                "b[ext=mp4][height>=360]/"
                "b[height>=360]/b"
            )
        else:
            h = self.selected_quality
            fmt = (
                f"bv*[vcodec^=avc1][ext=mp4][height<={h}][height>=360]+ba[ext=m4a]/"
                f"bv*[ext=mp4][height<={h}][height>=360]+ba[ext=m4a]/"
                f"b[ext=mp4][height<={h}][height>=360]/"
                f"b[height<={h}][height>=360]/b"
            )

        output = str(folder / "%(title).200s.%(ext)s")

        return [
            str(YTDLP),
            "--newline",
            "--no-playlist",
            "--ffmpeg-location",
            str(BIN),
            "-f",
            fmt,
            "--merge-output-format",
            "mp4",
            "-o",
            output,
            url
        ]

    def audio_command(self, url: str, folder: Path) -> list[str]:
        audio_format = "m4a" if self.m4a_radio.isChecked() else "mp3"
        output = str(folder / "%(title).200s.%(ext)s")

        return [
            str(YTDLP),
            "--newline",
            "--no-playlist",
            "--ffmpeg-location",
            str(BIN),
            "-x",
            "--audio-format",
            audio_format,
            "--audio-quality",
            self.window.settings["audio"].get("quality", "192K"),
            "-o",
            output,
            url
        ]

    def start_download(self) -> None:
        if self.process is not None:
            QMessageBox.warning(self, "Загрузка уже идёт", "Сначала останови текущую загрузку.")
            return

        url = self.url.text().strip()

        if not url:
            QMessageBox.warning(self, "Нет ссылки", "Вставь ссылку.")
            return

        if not self.check_tools():
            return

        folder = app_path(self.folder.text())
        folder.mkdir(parents=True, exist_ok=True)
        self.current_folder = folder

        self.window.settings["downloads"]["download_folder"] = self.folder.text().strip() or "downloads"
        self.window.settings["downloads"]["default_mode"] = "video" if self.video_radio.isChecked() else "audio"
        self.window.settings["audio"]["format"] = "m4a" if self.m4a_radio.isChecked() else "mp3"
        save_settings(self.window.settings)

        if self.video_radio.isChecked():
            command = self.video_command(url, folder)
        else:
            command = self.audio_command(url, folder)

        self.window.logger.write("")
        self.window.logger.write("=== Download started ===")
        self.window.logger.write(" ".join(f'"{x}"' if " " in x else x for x in command))
        self.window.logger.write("")

        self.process = QProcess(self)
        self.process.setProgram(command[0])
        self.process.setArguments(command[1:])
        self.process.setProcessChannelMode(QProcess.MergedChannels)

        self.process.readyReadStandardOutput.connect(self.on_output)
        self.process.finished.connect(self.on_finished)
        self.process.errorOccurred.connect(self.on_error)

        self.progress.setValue(0)
        self.status.setText("Загрузка запущена. Подробности пишутся в TXT-лог.")
        self.download_btn.setEnabled(False)
        self.stop_btn.setEnabled(True)

        self.process.start()

    def stop_download(self) -> None:
        if self.process:
            self.process.kill()
            self.status.setText("Загрузка остановлена.")
            self.window.logger.write("Download stopped by user.")

    def on_output(self) -> None:
        if not self.process:
            return

        data = bytes(self.process.readAllStandardOutput()).decode("utf-8", errors="replace")

        if not data:
            return

        self.window.logger.block(data)

        for line in data.splitlines():
            match = re.search(r"\[download\]\s+(\d+(?:\.\d+)?)%", line)

            if match:
                percent = int(float(match.group(1)))
                percent = max(0, min(100, percent))
                self.progress.setValue(percent)
                self.status.setText(f"Загрузка: {percent}%")

            if "[Merger]" in line:
                self.status.setText("Объединение видео и аудио...")

            if "[ExtractAudio]" in line:
                self.status.setText("Извлечение аудио...")

    def on_finished(self, exit_code: int, exit_status) -> None:
        if exit_code == 0:
            self.progress.setValue(100)
            self.status.setText("Готово. Файл скачан.")

            if self.current_folder:
                file = newest_file(self.current_folder)

                if file:
                    add_recent(self.window.settings, file)
                    self.window.refresh_recent()

            self.window.tray_msg("YouWizard", "Загрузка завершена.")
            self.window.logger.write("=== Download finished ===")
        else:
            self.status.setText(f"Ошибка загрузки. Код: {exit_code}. Подробности в TXT-логе.")
            self.window.tray_msg("YouWizard", "Ошибка загрузки.")
            self.window.logger.write(f"=== Download failed: {exit_code} ===")

        self.process = None
        self.download_btn.setEnabled(True)
        self.stop_btn.setEnabled(False)

    def on_error(self) -> None:
        self.status.setText("Ошибка запуска yt-dlp.")
        self.window.logger.write("QProcess error.")

        self.process = None
        self.download_btn.setEnabled(True)
        self.stop_btn.setEnabled(False)


class HistoryPage(QWidget):
    def __init__(self, window: "MainWindow"):
        super().__init__()
        self.window = window

        layout = QVBoxLayout(self)
        layout.setContentsMargins(24, 22, 24, 22)
        layout.setSpacing(12)

        title = QLabel("Загружено")
        title.setObjectName("PageTitle")

        subtitle = QLabel("Последние 5 скачанных файлов.")
        subtitle.setObjectName("Muted")
        subtitle.setWordWrap(True)

        self.recent = RecentList(self.window, "История скачивания")

        open_folder = QPushButton("Открыть папку загрузок")
        open_folder.setObjectName("Primary")
        open_folder.setMinimumHeight(48)
        open_folder.clicked.connect(self.open_folder)

        layout.addWidget(title)
        layout.addWidget(subtitle)
        layout.addWidget(self.recent)
        layout.addWidget(open_folder)
        layout.addStretch()

    def refresh(self) -> None:
        self.recent.refresh()

    def open_folder(self) -> None:
        folder = app_path(self.window.settings["downloads"].get("download_folder", "downloads"))
        folder.mkdir(parents=True, exist_ok=True)
        open_path(folder)


class SettingsPage(QWidget):
    def __init__(self, window: "MainWindow"):
        super().__init__()
        self.window = window

        layout = QVBoxLayout(self)
        layout.setContentsMargins(24, 22, 24, 22)
        layout.setSpacing(12)

        title = QLabel("Настройки")
        title.setObjectName("PageTitle")

        subtitle = QLabel("Основные параметры приложения.")
        subtitle.setObjectName("Muted")
        subtitle.setWordWrap(True)

        card = Card()
        card_layout = QVBoxLayout(card)
        card_layout.setContentsMargins(16, 16, 16, 16)
        card_layout.setSpacing(12)

        folder_label = QLabel("Папка загрузок")
        folder_label.setObjectName("SectionTitle")

        folder_row = QHBoxLayout()
        folder_row.setSpacing(10)

        self.folder = QLineEdit()
        self.folder.setMinimumHeight(46)
        self.folder.setText(self.window.download_folder())

        choose = QPushButton("Выбрать")
        choose.setMinimumHeight(46)
        choose.clicked.connect(self.choose_folder)

        folder_row.addWidget(self.folder, 1)
        folder_row.addWidget(choose)

        self.high_res = QCheckBox("Показывать 2K / 4K / 8K")
        self.high_res.setChecked(
            bool(self.window.settings["downloads"].get("show_high_res_options", False))
        )

        save = QPushButton("Сохранить")
        save.setObjectName("Primary")
        save.setMinimumHeight(48)
        save.clicked.connect(self.save)

        open_settings = QPushButton("Открыть settings.json")
        open_settings.setMinimumHeight(44)
        open_settings.clicked.connect(lambda: open_path(SETTINGS_FILE))

        open_logs = QPushButton("Открыть логи")
        open_logs.setMinimumHeight(44)
        open_logs.clicked.connect(lambda: open_path(logs_dir(self.window.settings)))

        self.info = QLabel()
        self.info.setObjectName("Muted")
        self.info.setWordWrap(True)

        card_layout.addWidget(folder_label)
        card_layout.addLayout(folder_row)
        card_layout.addWidget(self.high_res)
        card_layout.addWidget(save)
        card_layout.addWidget(open_settings)
        card_layout.addWidget(open_logs)
        card_layout.addWidget(self.info)

        layout.addWidget(title)
        layout.addWidget(subtitle)
        layout.addWidget(card)
        layout.addStretch()

        self.update_info()

    def choose_folder(self) -> None:
        folder = QFileDialog.getExistingDirectory(
            self,
            "Выбрать папку загрузок",
            str(app_path(self.folder.text())),
            QFileDialog.Option.DontUseNativeDialog
        )

        if folder:
            self.folder.setText(folder)

    def save(self) -> None:
        self.window.settings["downloads"]["download_folder"] = self.folder.text().strip() or "downloads"
        self.window.settings["downloads"]["show_high_res_options"] = self.high_res.isChecked()
        save_settings(self.window.settings)

        self.window.download_page.rebuild_quality_buttons()
        self.window.download_page.folder.setText(self.window.download_folder())
        self.update_info()

        QMessageBox.information(self, "Сохранено", "Настройки сохранены.")

    def update_info(self) -> None:
        self.info.setText(
            f"yt-dlp.exe: {'найден' if YTDLP.exists() else 'не найден'}\n"
            f"ffmpeg.exe: {'найден' if FFMPEG.exists() else 'не найден'}\n"
            f"ffprobe.exe: {'найден' if FFPROBE.exists() else 'не найден'}\n"
            f"Логи: {logs_dir(self.window.settings)}"
        )


class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()

        self.settings = load_settings()
        self.logger = Logger(self.settings)

        cleanup_logs(self.settings)

        self.setWindowTitle(APP_NAME)
        self.resize(1040, 680)
        self.setMinimumSize(820, 560)

        self.tray = QSystemTrayIcon(self)
        self.tray.setToolTip(APP_NAME)
        self.setup_tray()

        self.cleanup_timer = QTimer(self)
        self.cleanup_timer.timeout.connect(self.cleanup_logs)

        try:
            minutes = int(self.settings["logs"].get("cleanup_interval_minutes", 60))
        except Exception:
            minutes = 60

        self.cleanup_timer.start(max(1, minutes) * 60 * 1000)

        background = QWidget()
        background.setObjectName("Background")

        background_layout = QHBoxLayout(background)
        background_layout.setContentsMargins(14, 14, 14, 14)

        shell = QFrame()
        shell.setObjectName("Shell")

        shell_layout = QHBoxLayout(shell)
        shell_layout.setContentsMargins(0, 0, 0, 0)
        shell_layout.setSpacing(0)

        sidebar = QFrame()
        sidebar.setObjectName("Sidebar")
        sidebar.setFixedWidth(220)

        side_layout = QVBoxLayout(sidebar)
        side_layout.setContentsMargins(14, 18, 14, 18)
        side_layout.setSpacing(10)

        logo = QLabel("YouWizard")
        logo.setObjectName("Logo")

        desc = QLabel("Media downloader")
        desc.setObjectName("Muted")

        side_layout.addWidget(logo)
        side_layout.addWidget(desc)
        side_layout.addSpacing(18)

        self.stack = QStackedWidget()
        self.stack.setObjectName("Stack")

        self.download_page = DownloadPage(self)
        self.history_page = HistoryPage(self)
        self.settings_page = SettingsPage(self)

        self.stack.addWidget(make_scroll_page(self.download_page))
        self.stack.addWidget(make_scroll_page(self.history_page))
        self.stack.addWidget(make_scroll_page(self.settings_page))

        self.nav_buttons = []

        self.add_nav(side_layout, "Скачать", 0)
        self.add_nav(side_layout, "Загружено", 1)
        self.add_nav(side_layout, "Настройки", 2)

        side_layout.addStretch()

        exit_btn = QPushButton("Выход")
        exit_btn.setMinimumHeight(44)
        exit_btn.clicked.connect(QApplication.quit)
        side_layout.addWidget(exit_btn)

        shell_layout.addWidget(sidebar)
        shell_layout.addWidget(self.stack, 1)

        background_layout.addWidget(shell)
        self.setCentralWidget(background)

        self.nav_buttons[0].setChecked(True)

        self.apply_style()
        self.logger.write("Application ready.")

    def download_folder(self) -> str:
        return self.settings["downloads"].get("download_folder", "downloads")

    def add_nav(self, layout: QVBoxLayout, text: str, index: int) -> None:
        btn = NavButton(text)
        btn.clicked.connect(lambda checked=False, i=index: self.switch(i))
        layout.addWidget(btn)
        self.nav_buttons.append(btn)

    def switch(self, index: int) -> None:
        self.stack.setCurrentIndex(index)

        for i, btn in enumerate(self.nav_buttons):
            btn.setChecked(i == index)

        if index == 1:
            self.history_page.refresh()

        if index == 2:
            self.settings_page.update_info()

    def refresh_recent(self) -> None:
        self.download_page.refresh_recent()
        self.history_page.refresh()

    def setup_tray(self) -> None:
        menu = QMenu()

        open_action = QAction("Открыть YouWizard", self)
        open_action.triggered.connect(self.show_window)

        logs_action = QAction("Открыть логи", self)
        logs_action.triggered.connect(lambda: open_path(logs_dir(self.settings)))

        exit_action = QAction("Выход", self)
        exit_action.triggered.connect(QApplication.quit)

        menu.addAction(open_action)
        menu.addAction(logs_action)
        menu.addSeparator()
        menu.addAction(exit_action)

        self.tray.setContextMenu(menu)
        self.tray.show()

    def show_window(self) -> None:
        self.show()
        self.raise_()
        self.activateWindow()

    def tray_msg(self, title: str, text: str) -> None:
        if self.tray.isVisible():
            self.tray.showMessage(title, text, QSystemTrayIcon.Information, 3000)

    def cleanup_logs(self) -> None:
        cleanup_logs(self.settings)
        self.logger.write("Log cleanup completed.")

    def closeEvent(self, event) -> None:
        if self.settings["app"].get("close_to_tray", True):
            event.ignore()
            self.hide()
            self.tray_msg(APP_NAME, "Программа продолжает работать в фоне.")
            self.logger.write("Window hidden to tray.")
        else:
            event.accept()

    def apply_style(self) -> None:
        self.setStyleSheet("""
            * {
                outline: 0;
                border-radius: 0px;
            }

            QWidget {
                background: #1E1E1E;
                color: #F5F5F7;
                font-family: "Segoe UI";
                font-size: 14px;
            }

            #Background {
                background: #1E1E1E;
            }

            #Shell {
                background: #202020;
                border: 1px solid #3A3A3C;
            }

            #Sidebar {
                background: #181818;
                border-right: 1px solid #333333;
            }

            #Stack {
                background: #202020;
                border: none;
            }

            #PageScroll {
                background: #202020;
                border: none;
            }

            #PageScroll QWidget {
                background: #202020;
            }

            #Logo {
                background: transparent;
                color: white;
                font-size: 26px;
                font-weight: 800;
            }

            #PageTitle {
                background: transparent;
                color: white;
                font-size: 30px;
                font-weight: 800;
            }

            #SectionTitle {
                background: transparent;
                color: white;
                font-size: 15px;
                font-weight: 700;
            }

            #Muted {
                background: transparent;
                color: #A9A9B2;
            }

            #Card {
                background: #2A2A2D;
                border: 1px solid #3C3C40;
            }

            #RecentRow {
                background: #242426;
                border: 1px solid #3A3A3D;
            }

            #RecentText {
                background: transparent;
                color: #F5F5F7;
            }

            QPushButton {
                background: #303034;
                color: white;
                border: 1px solid #4A4A50;
                padding: 8px 16px;
                font-weight: 600;
            }

            QPushButton:hover {
                background: #3A3A40;
                border-color: #5A5A62;
            }

            QPushButton:pressed {
                background: #252529;
            }

            QPushButton:checked {
                background: #0A84FF;
                border-color: #0A84FF;
                color: white;
            }

            QPushButton:disabled {
                background: #26262A;
                color: #777780;
                border-color: #333338;
            }

            #Primary {
                background: #0A84FF;
                border-color: #0A84FF;
                color: white;
            }

            #Primary:hover {
                background: #2B94FF;
            }

            QLineEdit {
                background: #151515;
                color: white;
                border: 1px solid #4A4A50;
                padding: 9px 12px;
                selection-background-color: #0A84FF;
            }

            QLineEdit:hover {
                border-color: #62626A;
            }

            QLineEdit:focus {
                border-color: #0A84FF;
            }

            QRadioButton,
            QCheckBox {
                background: transparent;
                color: #F5F5F7;
                spacing: 10px;
                padding: 7px;
            }

            QRadioButton:hover,
            QCheckBox:hover {
                background: #303034;
            }

            QRadioButton#QualityButton {
                background: #151515;
                border: 1px solid #4A4A50;
                padding: 8px 12px;
                min-width: 82px;
                font-weight: 600;
            }

            QRadioButton#QualityButton:hover {
                border-color: #62626A;
                background: #222226;
            }

            QRadioButton#QualityButton:checked {
                background: #0A84FF;
                border-color: #0A84FF;
                color: white;
            }

            QRadioButton#QualityButton::indicator {
                width: 0px;
                height: 0px;
            }

            QRadioButton::indicator {
                width: 18px;
                height: 18px;
                border: 1px solid #686870;
                background: #151515;
            }

            QRadioButton::indicator:checked {
                background: #0A84FF;
                border: 1px solid #0A84FF;
            }

            QCheckBox::indicator {
                width: 18px;
                height: 18px;
                border: 1px solid #686870;
                background: #151515;
            }

            QCheckBox::indicator:checked {
                background: #0A84FF;
                border: 1px solid #0A84FF;
            }

            QProgressBar {
                background: #151515;
                color: white;
                border: 1px solid #4A4A50;
                text-align: center;
            }

            QProgressBar::chunk {
                background: #0A84FF;
            }

            QMenu {
                background: #2A2A2D;
                color: white;
                border: 1px solid #4A4A50;
            }

            QMenu::item {
                padding: 8px 22px;
            }

            QMenu::item:selected {
                background: #0A84FF;
            }

            QMessageBox {
                background: #1E1E1E;
                color: white;
            }

            QMessageBox QLabel {
                color: white;
                background: transparent;
            }

            QFileDialog {
                background: #1E1E1E;
                color: white;
            }

            QScrollBar:vertical {
                background: #202020;
                width: 12px;
                margin: 0px;
                border: none;
            }

            QScrollBar::handle:vertical {
                background: #4A4A50;
                min-height: 28px;
            }

            QScrollBar::handle:vertical:hover {
                background: #5A5A62;
            }

            QScrollBar::add-line:vertical,
            QScrollBar::sub-line:vertical {
                height: 0px;
                background: transparent;
            }

            QScrollBar::add-page:vertical,
            QScrollBar::sub-page:vertical {
                background: transparent;
            }

            QScrollBar:horizontal {
                background: #202020;
                height: 12px;
                margin: 0px;
                border: none;
            }

            QScrollBar::handle:horizontal {
                background: #4A4A50;
                min-width: 28px;
            }

            QScrollBar::handle:horizontal:hover {
                background: #5A5A62;
            }

            QScrollBar::add-line:horizontal,
            QScrollBar::sub-line:horizontal {
                width: 0px;
                background: transparent;
            }

            QScrollBar::add-page:horizontal,
            QScrollBar::sub-page:horizontal {
                background: transparent;
            }
        """)


def main() -> None:
    app = QApplication(sys.argv)
    app.setApplicationName(APP_NAME)
    app.setStyle("Fusion")
    apply_dark_palette(app)

    window = MainWindow()
    window.show()

    sys.exit(app.exec())


if __name__ == "__main__":
    main()